package view;

import dao.VeiculoDAO;
import dao.excel.VeiculoExcelDAO;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Veiculo;

/**
 *
 * @author Davi
 */
public class TelaVeiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVeiculo.class.getName());

    /**
     * Creates new form TelaVeiculo
     */
    public TelaVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        btnSalvarTXT = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Placa");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Ano de Fabricação");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chevrolet", "Fiat", "Mercedes", "BMW" }));

        btnSalvarTXT.setText("Cadastrar");
        btnSalvarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTXTActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvarTXT)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(311, 311, 311))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 379, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addGap(54, 54, 54))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbStatus, cbTipo, txtAno, txtID, txtModelo, txtPlaca});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarTXT)
                    .addComponent(btnVoltar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTXTActionPerformed
          try {
    // Verificar campos vazios
    if (txtID.getText().trim().isEmpty() ||
        txtPlaca.getText().trim().isEmpty() ||
        txtModelo.getText().trim().isEmpty() ||
        txtAno.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        return;
    }

    // ID numérico
    int id;
    try {
        id = Integer.parseInt(txtID.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "O ID deve conter apenas números!");
        return;
    }

    // ID duplicado
    try (java.io.BufferedReader br = new java.io.BufferedReader(
            new java.io.FileReader("BancodeDadosVeiculos.txt"))) {

        String linha;
        while ((linha = br.readLine()) != null) {
            if (linha.startsWith("ID:")) {
                int idExistente = Integer.parseInt(linha.split(":")[1].trim());
                if (idExistente == id) {
                    JOptionPane.showMessageDialog(this,
                        "Já existe um veículo cadastrado com esse ID!");
                    return;
                }
            }
        }
    }

    // Ano numérico
    int ano;
    try {
        ano = Integer.parseInt(txtAno.getText().trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "O ano deve conter apenas números!");
        return;
    }

    // Ano válido
    if (ano < 1900 || ano > 2025) {
        JOptionPane.showMessageDialog(this, "Ano inválido! Digite entre 1900 e 2025.");
        return;
    }

    // Placa sem minúsculas
    String placa = txtPlaca.getText().trim();
    if (!placa.equals(placa.toUpperCase())) {
        JOptionPane.showMessageDialog(this, "A placa não pode conter letras minúsculas!");
        return;
    }

    // Formato da placa
    String padrao1 = "^[A-Z]{3}[0-9][A-Z][0-9]{2}$";  
    String padrao2 = "^[A-Z]{3}-[0-9]{4}$";
    if (!placa.matches(padrao1) && !placa.matches(padrao2)) {
        JOptionPane.showMessageDialog(this, "Placa inválida! Use ABC1D23 ou ABC-1234");
        return;
    }

    // Placa duplicada
    try (java.io.BufferedReader br = new java.io.BufferedReader(
            new java.io.FileReader("BancodeDadosVeiculos.txt"))) {

        String linha;
        while ((linha = br.readLine()) != null) {
            if (linha.startsWith("Placa:")) {
                String existente = linha.split(":", 2)[1].trim();
                if (existente.equalsIgnoreCase(placa)) {
                    JOptionPane.showMessageDialog(this, "Essa placa já está cadastrada!");
                    return;
                }
            }
        }
    }

    // Criar objeto
    String modelo = txtModelo.getText().trim();
    String tipo = cbTipo.getSelectedItem().toString();
    String status = cbStatus.getSelectedItem().toString();

    Veiculo v = new Veiculo(id, tipo, modelo, placa, ano, status);

    // Salvar em TXT
    VeiculoDAO dao = new VeiculoDAO();
    dao.adicionar(v);

    // Salvar em Excel
    dao.excel.VeiculoExcelDAO excelDAO = new dao.excel.VeiculoExcelDAO();
    excelDAO.salvarEmExcel(v);

    JOptionPane.showMessageDialog(this,
        "Veículo salvo no TXT e Excel com sucesso!");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage());
}

    }//GEN-LAST:event_btnSalvarTXTActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVeiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarTXT;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
