/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.MovimentacaoDAO;
import dao.VeiculoDAO;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.List;
import javax.swing.JOptionPane;
import model.Veiculo;

/**
 *
 * @author Davi
 */
public class TelaVisualizarDespesas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVisualizarDespesas.class.getName());

    /**
     * Creates new form TelaVisualizarDespesas
     */
    public TelaVisualizarDespesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnGerar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jButton1.setText("Somatorio Mês");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Somatorio IPVA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Multas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Inativos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Combustivel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Despesa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton6)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton3)
                        .addGap(46, 46, 46)
                        .addComponent(btnGerar)))
                .addGap(39, 39, 39)
                .addComponent(jButton5)
                .addGap(36, 36, 36)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnGerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        txtArea.setText(""); // limpar área

        try (BufferedReader br = new BufferedReader(new FileReader("Movimentacoes.txt"))) {

            StringBuilder sb = new StringBuilder();
            String linha;

            while ((linha = br.readLine()) != null) {
                sb.append(linha).append("\n");
            }

            txtArea.setText(sb.toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao ler Movimentacoes.txt\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

    // ==== CAPTURAR MÊS ====
    String mesStr = JOptionPane.showInputDialog(this, "Mês (1-12):");
    if (mesStr == null) return; // cancelou

    // validação imediata: máximo 2 caracteres
    if (mesStr.trim().length() > 2) {
        JOptionPane.showMessageDialog(this, "O mês deve conter no máximo 2 dígitos.");
        return;
    }

    int mes = Integer.parseInt(mesStr.trim());

    // validação imediata: 1 a 12
    if (mes < 1 || mes > 12) {
        JOptionPane.showMessageDialog(this, "Mês inválido! Digite um mês entre 1 e 12.");
        return;
    }

    // ==== CAPTURAR ANO ====
    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");
    if (anoStr == null) return;

    int ano = Integer.parseInt(anoStr.trim());

    if (anoStr.trim().length() != 4) {
        JOptionPane.showMessageDialog(this, "Ano inválido! Informe exatamente 4 dígitos.");
        return;
    }

    // ==== EXECUTAR O MÉTODO ====
    MovimentacaoDAO dao = new MovimentacaoDAO();
    double total = dao.somatorioDespesasPorMes(mes, ano);

    java.text.NumberFormat nf =
        java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt", "BR"));

    txtArea.setText("");
    txtArea.append("===== RELATÓRIO DE DESPESAS DA FROTA =====\n\n");
    txtArea.append("Período pesquisado: " + String.format("%02d/%d", mes, ano) + "\n");
    txtArea.append("-------------------------------------------\n");
    txtArea.append("Total de despesas: " + nf.format(total) + "\n");

} catch (NumberFormatException nfe) {
    JOptionPane.showMessageDialog(this, "Entrada inválida! Insira apenas números.");
} catch (IllegalArgumentException iae) {
    JOptionPane.showMessageDialog(this, iae.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");
    if (anoStr == null) return; // cancelar

    anoStr = anoStr.trim();

    // --- VALIDAÇÃO PARA ACEITAR SOMENTE NÚMEROS ---
    if (!anoStr.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, 
              "Digite apenas números para o ano (ex: 2025).");
        return;
    }

    int ano = Integer.parseInt(anoStr);

    MovimentacaoDAO dao = new MovimentacaoDAO();
    double total = dao.somatorioIPVAporAno(ano);

    java.text.NumberFormat nf =
            java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt","BR"));

    String msg = "Somatório de IPVA da frota no ano " + ano + ":\n\n" +
                 nf.format(total);

    txtArea.setText(msg);

} catch (IllegalArgumentException iae) {
    JOptionPane.showMessageDialog(this, iae.getMessage());

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Erro inesperado!");
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
    String mesStr = JOptionPane.showInputDialog(this, "Mês (1-12):");
    if (mesStr == null) return;

    // valida tamanho do mês digitado
    if (mesStr.trim().length() > 2) {
        JOptionPane.showMessageDialog(this, "Digite apenas 2 dígitos para o mês!");
        return;
    }

    int mes = Integer.parseInt(mesStr.trim());

    // valida faixa do mês
    if (mes < 1 || mes > 12) {
        JOptionPane.showMessageDialog(this, "Mês inválido! Informe um valor entre 1 e 12.");
        return;
    }

    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");
    if (anoStr == null) return;

    // valida 4 dígitos
    if (anoStr.trim().length() != 4) {
        JOptionPane.showMessageDialog(this, "Ano inválido!");
        return;
    }

    int ano = Integer.parseInt(anoStr.trim());

    MovimentacaoDAO dao = new MovimentacaoDAO();
    String resultado = dao.listarMultasPorMes(mes, ano);

    txtArea.setText(resultado);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Entrada inválida! Digite apenas números.");
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    VeiculoDAO dao = new VeiculoDAO();
    String resultado = dao.listarVeiculosInativos();
    txtArea.setText(resultado);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {

    String mesStr = JOptionPane.showInputDialog(this, "Mês (1-12):");

    // Verificar se digitou algo
    if (mesStr == null || mesStr.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Você deve digitar um mês!");
        return;
    }

    // Verificar número máximo de caracteres
    if (mesStr.length() > 2) {
        JOptionPane.showMessageDialog(this, "Mês inválido! Digite apenas 1 ou 2 dígitos.");
        return;
    }

    int mes = Integer.parseInt(mesStr);

    // Verificar faixa válida
    if (mes < 1 || mes > 12) {
        JOptionPane.showMessageDialog(this, "Mês inválido! O mês deve estar entre 1 e 12.");
        return;
    }

    // AGORA pede o ano
    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");

    if (anoStr == null || anoStr.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Você deve digitar um ano!");
        return;
    }

    if (anoStr.length() != 4) {
        JOptionPane.showMessageDialog(this, "Ano inválido!");
        return;
    }

    int ano = Integer.parseInt(anoStr);

    // Chamar o DAO sem verificações (elas são feitas no botão)
    MovimentacaoDAO dao = new MovimentacaoDAO();
    String resultado = dao.listarDespesasCombustivelPorMes(mes, ano);

    txtArea.setText(resultado);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Digite apenas números!");
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
        int id = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite o ID do veículo:"));

        MovimentacaoDAO dao = new MovimentacaoDAO();
        String resultado = dao.listarDespesasPorVeiculo(id);

        txtArea.setText(resultado);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVisualizarDespesas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
