package view;

import dao.MovimentacaoDAO;
import dao.VeiculoDAO;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Veiculo;

/**
 *
 * @author Davi
 */
public class TelaVisualizarDespesas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVisualizarDespesas.class.getName());

    /**
     * Creates new form TelaVisualizarDespesas
     */
    public TelaVisualizarDespesas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/imagejar.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnSomatorioIpva = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnGerar = new javax.swing.JButton();
        btnInativos = new javax.swing.JButton();
        btnMultas = new javax.swing.JButton();
        btnCombustivel = new javax.swing.JButton();
        btnDespesasporVeiculo = new javax.swing.JButton();
        btnSomatoriomes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnSomatorioIpva.setBackground(new java.awt.Color(59, 130, 246));
        btnSomatorioIpva.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSomatorioIpva.setForeground(new java.awt.Color(255, 255, 255));
        btnSomatorioIpva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/somar.png"))); // NOI18N
        btnSomatorioIpva.setText("Somatorio IPVA");
        btnSomatorioIpva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomatorioIpvaActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(59, 130, 246));
        btnVoltar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnGerar.setBackground(new java.awt.Color(59, 130, 246));
        btnGerar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnGerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lista.png"))); // NOI18N
        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnInativos.setBackground(new java.awt.Color(59, 130, 246));
        btnInativos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnInativos.setForeground(new java.awt.Color(255, 255, 255));
        btnInativos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo x.png"))); // NOI18N
        btnInativos.setText("Inativos");
        btnInativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInativosActionPerformed(evt);
            }
        });

        btnMultas.setBackground(new java.awt.Color(59, 130, 246));
        btnMultas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnMultas.setForeground(new java.awt.Color(255, 255, 255));
        btnMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exclamaçao.png"))); // NOI18N
        btnMultas.setText("Multas");
        btnMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultasActionPerformed(evt);
            }
        });

        btnCombustivel.setBackground(new java.awt.Color(59, 130, 246));
        btnCombustivel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCombustivel.setForeground(new java.awt.Color(255, 255, 255));
        btnCombustivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/combustivel.png"))); // NOI18N
        btnCombustivel.setText("Combustivel");
        btnCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCombustivelActionPerformed(evt);
            }
        });

        btnDespesasporVeiculo.setBackground(new java.awt.Color(59, 130, 246));
        btnDespesasporVeiculo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnDespesasporVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnDespesasporVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardespesa.png"))); // NOI18N
        btnDespesasporVeiculo.setText("Despesa do Veiculo");
        btnDespesasporVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespesasporVeiculoActionPerformed(evt);
            }
        });

        btnSomatoriomes.setBackground(new java.awt.Color(59, 130, 246));
        btnSomatoriomes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnSomatoriomes.setForeground(new java.awt.Color(255, 255, 255));
        btnSomatoriomes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario.png"))); // NOI18N
        btnSomatoriomes.setText("Somatorio Mês");
        btnSomatoriomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomatoriomesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInativos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDespesasporVeiculo)
                    .addComponent(btnSomatorioIpva, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSomatoriomes)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDespesasporVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSomatoriomes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSomatorioIpva)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInativos)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        jPanel2.setBackground(new java.awt.Color(10, 26, 47));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GynLog");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        txtArea.setText(""); // limpar área

        try (BufferedReader br = new BufferedReader(new FileReader("BancodeDadosVeiculos.txt"))) {

            StringBuilder sb = new StringBuilder();
            String linha;

            while ((linha = br.readLine()) != null) {
                sb.append(linha).append("\n");
            }

            txtArea.setText(sb.toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao ler Movimentacoes.txt\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnSomatoriomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomatoriomesActionPerformed
        try {

    String mesStr = JOptionPane.showInputDialog(this, "Mês (1-12):");
    if (mesStr == null) return; // cancelou

    // validação imediata: máximo 2 caracteres
    if (mesStr.trim().length() > 2) {
        JOptionPane.showMessageDialog(this, "O mês deve conter no máximo 2 dígitos.");
        return;
    }

    int mes = Integer.parseInt(mesStr.trim());

    // validação imediata: 1 a 12
    if (mes < 1 || mes > 12) {
        JOptionPane.showMessageDialog(this, "Mês inválido! Digite um mês entre 1 e 12.");
        return;
    }

    // ==== CAPTURAR ANO ====
    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");
    if (anoStr == null) return;

    int ano = Integer.parseInt(anoStr.trim());

    if (anoStr.trim().length() != 4) {
        JOptionPane.showMessageDialog(this, "Ano inválido! Informe exatamente 4 dígitos.");
        return;
    }

    // ==== EXECUTAR O MÉTODO ====
    MovimentacaoDAO dao = new MovimentacaoDAO();
    double total = dao.somatorioDespesasPorMes(mes, ano);

    java.text.NumberFormat nf =
        java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt", "BR"));

    txtArea.setText("");
    txtArea.append("===== RELATÓRIO DE DESPESAS DA FROTA =====\n\n");
    txtArea.append("Período pesquisado: " + String.format("%02d/%d", mes, ano) + "\n");
    txtArea.append("-------------------------------------------\n");
    txtArea.append("Total de despesas: " + nf.format(total) + "\n");

} catch (NumberFormatException nfe) {
    JOptionPane.showMessageDialog(this, "Entrada inválida! Insira apenas números.");
} catch (IllegalArgumentException iae) {
    JOptionPane.showMessageDialog(this, iae.getMessage());
}

    }//GEN-LAST:event_btnSomatoriomesActionPerformed

    private void btnSomatorioIpvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomatorioIpvaActionPerformed
        try {
    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");
    if (anoStr == null) return; // cancelar

    anoStr = anoStr.trim();

    // --- VALIDAÇÃO PARA ACEITAR SOMENTE NÚMEROS ---
    if (!anoStr.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, 
              "Digite apenas números para o ano (ex: 2025).");
        return;
    }

    int ano = Integer.parseInt(anoStr);

    MovimentacaoDAO dao = new MovimentacaoDAO();
    double total = dao.somatorioIPVAporAno(ano);

    java.text.NumberFormat nf =
            java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("pt","BR"));

    String msg = "Somatório de IPVA da frota no ano " + ano + ":\n\n" +
                 nf.format(total);

    txtArea.setText(msg);

} catch (IllegalArgumentException iae) {
    JOptionPane.showMessageDialog(this, iae.getMessage());

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Erro inesperado!");
}

    }//GEN-LAST:event_btnSomatorioIpvaActionPerformed

    private void btnMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultasActionPerformed
        try {
    String mesStr = JOptionPane.showInputDialog(this, "Mês (1-12):");
    if (mesStr == null) return;

    // valida tamanho do mês digitado
    if (mesStr.trim().length() > 2) {
        JOptionPane.showMessageDialog(this, "Digite apenas 2 dígitos para o mês!");
        return;
    }

    int mes = Integer.parseInt(mesStr.trim());

    // valida faixa do mês
    if (mes < 1 || mes > 12) {
        JOptionPane.showMessageDialog(this, "Mês inválido! Informe um valor entre 1 e 12.");
        return;
    }

    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");
    if (anoStr == null) return;

    // valida 4 dígitos
    if (anoStr.trim().length() != 4) {
        JOptionPane.showMessageDialog(this, "Ano inválido!");
        return;
    }

    int ano = Integer.parseInt(anoStr.trim());

    MovimentacaoDAO dao = new MovimentacaoDAO();
    String resultado = dao.listarMultasPorMes(mes, ano);

    txtArea.setText(resultado);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Entrada inválida! Digite apenas números.");
}

    }//GEN-LAST:event_btnMultasActionPerformed

    private void btnInativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInativosActionPerformed
    VeiculoDAO dao = new VeiculoDAO();
    String resultado = dao.listarVeiculosInativos();
    txtArea.setText(resultado);
    }//GEN-LAST:event_btnInativosActionPerformed

    private void btnCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCombustivelActionPerformed
        try {

    String mesStr = JOptionPane.showInputDialog(this, "Mês (1-12):");

    // Verificar se digitou algo
    if (mesStr == null || mesStr.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Você deve digitar um mês!");
        return;
    }

    // Verificar número máximo de caracteres
    if (mesStr.length() > 2) {
        JOptionPane.showMessageDialog(this, "Mês inválido! Digite apenas 1 ou 2 dígitos.");
        return;
    }

    int mes = Integer.parseInt(mesStr);

    // Verificar faixa válida
    if (mes < 1 || mes > 12) {
        JOptionPane.showMessageDialog(this, "Mês inválido! O mês deve estar entre 1 e 12.");
        return;
    }

    // AGORA pede o ano
    String anoStr = JOptionPane.showInputDialog(this, "Ano (ex: 2025):");

    if (anoStr == null || anoStr.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Você deve digitar um ano!");
        return;
    }

    if (anoStr.length() != 4) {
        JOptionPane.showMessageDialog(this, "Ano inválido!");
        return;
    }

    int ano = Integer.parseInt(anoStr);

    // Chamar o DAO sem verificações (elas são feitas no botão)
    MovimentacaoDAO dao = new MovimentacaoDAO();
    String resultado = dao.listarDespesasCombustivelPorMes(mes, ano);

    txtArea.setText(resultado);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Digite apenas números!");
}

    }//GEN-LAST:event_btnCombustivelActionPerformed

    private void btnDespesasporVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespesasporVeiculoActionPerformed
        try {
    String entrada = JOptionPane.showInputDialog(
            this, 
            "Digite o ID do veículo:"
    );

    if (entrada == null) return;

    entrada = entrada.trim();

    if (entrada.isEmpty()) {
        throw new NumberFormatException("Entrada vazia");
    }

    if (!entrada.matches("\\d+")) {
        throw new NumberFormatException("Contém caracteres inválidos");
    }

    int id = Integer.parseInt(entrada);

    MovimentacaoDAO dao = new MovimentacaoDAO();
    String resultado = dao.listarDespesasPorVeiculo(id);

    txtArea.setText(resultado);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(
            this, 
            "ID inválido. Digite apenas números."
    );
}

    }//GEN-LAST:event_btnDespesasporVeiculoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVisualizarDespesas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCombustivel;
    private javax.swing.JButton btnDespesasporVeiculo;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnInativos;
    private javax.swing.JButton btnMultas;
    private javax.swing.JButton btnSomatorioIpva;
    private javax.swing.JButton btnSomatoriomes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
